name: Convert Markdown to PDF

on:
  push:
    paths:
      - "resumes/**/*.md"  # Trigger workflow on changes to Markdown files
      - "scripts/md_to_pdf.py"  # Trigger workflow on script updates
      - ".github/workflows/convert-markdown-to-pdf.yml"  # Trigger workflow on itself
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-pdfs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install Required Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install markdown pdfkit jinja2
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      # Step 4: Create 'generated_pdfs' directory
      - name: Prepare PDF Output Directory
        run: mkdir -p generated_pdfs

      # Step 5: Convert Markdown files to PDFs
      - name: Run Markdown-to-PDF Script
        run: |
          python3 scripts/md_to_pdf.py

      # Step 6: Debugging Step - Verify PDF Generation
      - name: Verify Generated PDFs
        run: |
          echo "Listing contents of 'generated_pdfs' directory:"
          ls -l generated_pdfs || echo "No PDFs found."

      # Step 7: Upload PDFs as Artifacts
      - name: Upload PDFs as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: generated-pdfs
          path: generated_pdfs/*.pdf
          if-no-files-found: warn
