name: Convert Markdown to PDF

on:
  push:
    paths:
      - "resumes/**/*.md"
      - "scripts/md_to_pdf.py"
      - ".github/workflows/convert-markdown-to-pdf.yml"
  workflow_dispatch:

jobs:
  generate-pdfs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install Required Dependencies
      - name: Install Required Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install markdown pdfkit
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf fonts-liberation ttf-mscorefonts-installer

      # Step 4: Create Output Directory
      - name: Create 'generated_pdfs' Directory
        run: mkdir -p generated_pdfs

      # Step 5: Convert Markdown Files to PDFs
      - name: Convert Markdown Files to PDFs
        run: |
          find resumes -name "*.md" -exec bash -c '
            for file; do
              base_name=$(basename "$file" .md)
              output_file="generated_pdfs/${base_name}.pdf"
              echo "Processing $file -> $output_file"
              python3 scripts/md_to_pdf.py "$file" "$output_file" || exit 1
            done
          ' bash {} +

      # Step 6: Debugging Step - Verify PDF Generation
      - name: Verify Generated PDFs
        run: |
          echo "Listing contents of 'generated_pdfs' directory:"
          ls -l generated_pdfs || echo "No PDFs found."

      # Step 7: Upload PDFs as Artifacts
      - name: Upload PDFs as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: generated-pdfs
          path: generated_pdfs/*.pdf
          if-no-files-found: warn
