name: Convert Markdown to PDF

on:
  push:
    paths:
      - "resumes/**/*.md"  # Trigger workflow when Markdown files in resumes folder are changed
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-pdfs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install Required Dependencies
      - name: Install Required Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown pdfkit jinja2
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      # Step 4: Create 'generated_pdfs' folder and check if it's created
      - name: Verify 'generated_pdfs' folder creation
        run: |
          mkdir -p generated_pdfs
          echo "Directory 'generated_pdfs' has been created at the root."
          ls -l generated_pdfs  # Verify if the folder exists

      # Step 5: Convert Markdown Files to PDF
      - name: Convert Markdown Files to PDF
        run: |
          find resumes -name "*.md" -exec bash -c '
            for file; do
              base_name=$(basename "$file" .md)
              echo "Processing $file"
              python scripts/md_to_pdf.py "$file" "generated_pdfs/${base_name}.pdf" || exit 1
              echo "Generated PDF: generated_pdfs/${base_name}.pdf"
            done
          ' bash {} +

      # Step 6: List generated PDFs for debugging
      - name: List generated PDFs
        run: |
          echo "Listing generated PDFs in 'generated_pdfs':"
          ls -l generated_pdfs/*.pdf || echo "No PDFs found"

      # Step 7: Upload generated PDFs as artifacts
      - name: Upload Generated PDFs as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: generated-pdfs
          path: generated_pdfs/*.pdf
