name: Convert Markdown to PDF

on:
  push:
    paths:
      - "resumes/**/*.md"  # Trigger workflow when Markdown files in the resumes folder change
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdfkit markdown

      # Step 4: Install wkhtmltopdf
      - name: Install wkhtmltopdf
        run: sudo apt-get install -y wkhtmltopdf

      # Step 5: Run the conversion script
      - name: Convert Markdown to PDF
        run: python scripts/md_to_pdf.py

      # Step 6: Commit and push the generated PDFs
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add resumes/*.pdf
          git commit -m "chore: add or update generated PDFs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
