name: Convert Markdown to PDF

on:
  # Trigger workflow on pushes to the main branch for changes in the 'resumes/*.md' files
  push:
    branches:
      - main
    paths:
      - "resumes/*.md"
  # Allow the workflow to be manually triggered via the Actions tab
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown pdfkit

      # Step 4: Install wkhtmltopdf
      - name: Install wkhtmltopdf
        run: sudo apt-get install -y wkhtmltopdf

      # Step 5: Convert Markdown files to PDFs
      - name: Convert Markdown to PDFs
        run: |
          python scripts/md_to_pdf.py resumes

      # Step 6: Commit and push generated PDFs
      - name: Commit and Push PDFs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add resumes/*.pdf
          git commit -m "chore: update generated PDFs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
