name: Convert Markdown to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'resumes/*.md'
  workflow_dispatch:

jobs:
  convert-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown pdfkit
          sudo apt-get install -y wkhtmltopdf

      - name: Generate PDFs from Markdown files
        run: python convert_markdown_to_pdf.py

      - name: Commit and push PDFs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add resumes/*.pdf
          git commit -m "chore: add or update generated PDFs"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
