name: Convert Markdown to PDF

on:
  push:
    paths:
      - "resumes/**/*.md"  # Trigger workflow on changes to Markdown files in 'resumes' folder
      - ".github/workflows/convert-markdown-to-pdf.yml"  # Trigger on workflow file changes
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-pdfs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install Required Dependencies
      - name: Install Required Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install markdown pdfkit jinja2
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      # Step 4: Create 'generated_pdfs' Folder
      - name: Create 'generated_pdfs' Folder
        run: mkdir -p generated_pdfs

      # Step 5: Convert Markdown Files to PDF
      - name: Convert Markdown Files to PDF
        run: |
          python3 scripts/md_to_pdf.py

      # Step 6: List Generated PDFs
      - name: List Generated PDFs
        run: |
          echo "Listing generated PDFs in 'generated_pdfs':"
          ls -l generated_pdfs/*.pdf || echo "No PDFs found"

      # Step 7: Upload PDFs as Artifacts
      - name: Upload PDFs as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: generated-pdfs
          path: generated_pdfs/*.pdf
          if-no-files-found: warn
