name: Convert Markdown to PDF

on:
  push:
    paths:
      - "resumes/**/*.md"  # Trigger workflow when Markdown files in resumes folder are changed
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-pdfs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install Required Dependencies
      - name: Install Required Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown pdfkit
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      # Step 4: Generate PDFs for Markdown files
      - name: Convert Markdown Files to PDF
        run: |
          mkdir -p generated_pdfs
          # Find all .md files in the resumes directory and process them
          find resumes -name "*.md" -exec bash -c '
            for file; do
              base_name=$(basename "$file" .md)
              echo "Processing $file"
              python scripts/md_to_pdf.py "$file" "generated_pdfs/${base_name}.pdf"
            done
          ' bash {} +

      # Step 5: Upload PDFs as Artifacts
      - name: Upload Generated PDFs
        uses: actions/upload-artifact@v3
        with:
          name: generated-pdfs
          path: generated_pdfs/*.pdf
